[package]
name = "gill-git"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git-repository = "0.29.0"
anyhow = "1.0.66"
tracing = "0.1"

[dev-dependencies]
sealed_test = "1.0.0"
speculoos = "0.11.0"