branch_whitelist = ["main"]
ignore_merge_commits = true
tag_prefix = "v"

pre_bump_hooks = [
    "SQLX_OFFLINE=true cargo test",
    "SQLX_OFFLINE=true cargo clippy",
    "cargo fmt --all",
    "SQLX_OFFLINE=true cargo build --release",
]

post_bump_hooks = [
    "git push",
    "git push origin --tags",
]

pre_package_bump_hooks = [
    "cargo set-version {{version}}"
]

[packages]
gill-app = { path = "crates/gill-app" }
gill-authorize-derive = { path = "crates/gill-authorize-derive", public_api = false }
gill-db = { path = "crates/gill-db", public_api = false }
gill-git = { path = "crates/gill-git", public_api = false }
gill-git-server = { path = "crates/gill-git-server" }
gill-markdown = { path = "crates/gill-markdown", public_api = false }
gill-settings = { path = "crates/gill-settings" }
gill-syntax = { path = "crates/gill-syntax" }
gill-web-markdown = { path = "crates/gill-web-markdown" }
syntect-plugin = { path = "crates/syntect-plugin", public_api = false }

[changelog]
template = "monorepo_remote"
package_template = "package_remote"
remote = "github.com"
repository = "gill"
owner = "oknozor"
authors = [
    { signature = "Paul Delafosse", username = "oknozor" },
]


