version: '3.9'
services:
  ruisseau:
    image: fserver:alpine
    depends_on:
      - postgres
    restart: always
    container_name: ruisseau
    ports:
      - "2222:22"
      - "3000:3000"
    networks:
      - local-dev


  postgres:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ruisseau
      POSTGRES_USER: ruisseau
      POSTGRES_PASSWORD: ruisseau
    ports:
      - "5432:5432"
    networks:
      - local-dev

  keycloakdb:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_PASSWORD: "keycloak"
    networks:
      - local-dev

  keycloak:
    image: jboss/keycloak:latest
    restart: unless-stopped
    depends_on:
      - keycloakdb
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloakdb
      DB_DATABASE: "keycloak"
      DB_USER: "keycloak"
      DB_PASSWORD: "keycloak"
      KEYCLOAK_IMPORT: /tmp/realm-export.json
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./../docker/realm-export.json:/tmp/realm-export.json
    networks:
      - local-dev

networks:
  local-dev: