version: '3.9'

services:
  git-server:
    image: fserver:alpine
    depends_on:
      - postgres
    restart: always
    container_name: ruisseau-git-server
    ports:
      - "2222:22"
      - "3000:3000"
    networks:
      - local-ruisseau

  postgres:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ruisseau
      POSTGRES_USER: ruisseau
      POSTGRES_PASSWORD: ruisseau
    ports:
      - "5432:5432"
    networks:
      - local-ruisseau
networks:
  local-ruisseau: