version: '3.9'
services:
  ruisseau:
    image: fserver:alpine
    depends_on:
      - postgres
    restart: always
    container_name: ruisseau
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres/ruisseau
      KEYCLOAK_URL: https://keycloak.cloud.hoohoot.org
    ports:
      - "3000:3000"
      - "2222:22"
    volumes:
      - ./docker/rbin:/home/git/bin
      - ./docker/githooks:/home/git/hooks
      - ./crates/ruisseau-api/assets:/home/git/assets
    entrypoint: /home/git/entrypoint-debug.sh


  postgres:
    image: docker.io/postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql