version: '3.9'
services:
  gill:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    depends_on:
      - postgres
    restart: always
    container_name: gill-app
    ports:
      - "3000:3000"
      - "2222:22"
    volumes:
      - ./docker/dev/home:/home/git
      - ./crates/gill-app/assets:/opt/gill/assets
      - ./docker/dev/config-instance-1.toml:/opt/gill/config.toml
    entrypoint: /home/git/entrypoint-debug.sh

  gill-2:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    depends_on:
      - postgres
    restart: always
    container_name: gill-app-2
    ports:
      - "3001:3000"
      - "12222:22"
    volumes:
      - ./docker/dev/home2:/home/git
      - ./crates/gill-app/assets:/opt/gill/assets
      - ./docker/dev/config-instance-2.toml:/opt/gill/config.toml
    entrypoint: /home/git/entrypoint-debug.sh

  postgres:
    image: docker.io/postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "gill"
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql