version: '3.9'
services:
  gill:
    image: gill-api:latest
    depends_on:
      - postgres
    restart: always
    container_name: gill-api
    environment:
      OAUTH_USER_INFO_URL: https://keycloak.cloud.hoohoot.org/auth/realms/hoohoot/protocol/openid-connect/userinfo
      DOMAIN: 127.0.0.1:3000
      DB_NAME: gill
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "3000:3000"
      - "2222:22"
    volumes:
      - ./docker/rbin:/home/git/bin
      - ./docker/githooks:/home/git/hooks
      - ./crates/gill-api/assets:/home/git/assets
    entrypoint: /home/git/entrypoint-debug.sh

  gill-apub:
    image: gill-apub:latest
    depends_on:
      - postgres
    restart: always
    container_name: gill-apub
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres/gill
    ports:
      - "3001:3001"

  postgres:
    image: docker.io/postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "gill"
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql