version: '3.9'
services:
  ruisseau:
    image: fserver:alpine
    depends_on:
      - postgres
    restart: always
    container_name: ruisseau
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres/ruisseau
      KEYCLOAK_URL: https://keycloak.cloud.hoohoot.org
    ports:
      - "3000:3000"
      - "2222:22"
    volumes:
      - ./docker/rbin:/home/git/bin
      - ./crates/ruisseau-api/assets:/home/git/assets
    entrypoint: /home/git/entrypoint-debug.sh


  postgres:
    image: docker.io/postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  keycloak:
    image: docker.io/jboss/keycloak:latest
    restart: unless-stopped
    depends_on:
      - postgres
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: "keycloak"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      KEYCLOAK_IMPORT: /tmp/realm-export.json
      PROXY_ADDRESS_FORWARDING: true
    volumes:
      - ./docker/realm-export.json:/tmp/realm-export.json
      - ./db-data/:/var/lib/postgresql/data/

  nginx:
    image: nginx:1
    container_name: nginx
    restart: on-failure
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"