version: '3.9'

services:
  gill:
    build:
      dockerfile: Dockerfile
      context: ./
    image: "gillpub/gill:latest-arm64v8"
    restart: unless-stopped
    container_name: gill
    environment:
      GILL_DB_NAME: gill
      GILL_DB_HOST: 192.168.0.17
      GILL_DB_PORT: 5432
      GILL_DB_USER: postgres
      GILL_DB_PASSWORD: postgres
      GILL_GILL_ASSETS: /opt/gill/assets
      GILL_OAUTH_CLIENT_ID: gill-okno
      GILL_OAUTH_CLIENT_SECRET: VGCTr6m0kVQUCgddI4SW2iCX0Bo3Nqno
      GILL_OAUTH_PROVIDER: https://keycloak.cloud.hoohoot.org
      GILL_OAUTH_USER_INFO_URL: /auth/realms/hoohoot/protocol/openid-connect/userinfo
      GILL_OAUTH_TOKEN_URL: /auth/realms/hoohoot/protocol/openid-connect/token
      GILL_OAUTH_AUTH_URL: /auth/realms/hoohoot/protocol/openid-connect/auth
      GILL_DOMAIN: home-raspberry.gill.pub
      GILL_PORT: 3000
      GILL_SSH_PORT: 2222
      GILL_DEBUG: false
    env_file:
      - sshd.env
    ports:
      - "3000:3000"
      - "2222:22"
    volumes:
      - ./gill_data:/home/git
    networks:
      - gill

volumes:
  gill_data:
networks:
  gill: