[package]
name = "ruisseau-api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.0-rc.4", features = ["json", "headers", "macros"] }
axum-macros = "0.3.0-rc.2"
tokio = { version = "1.21.2", features = ["full"] }
sqlx = { version = "0.6.2", features = ["runtime-tokio-rustls", "any", "postgres", "offline"] }
eyre = "0.6.8"
serde_json = "1.0.87"
serde = { version = "1.0.147", features = ["derive"] }
ruisseau-git = { path = "../ruisseau-git" }
tower-http = { version = "0.3.0", features = ["trace", "fs"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
aide = { version = "0.7.1", features = ["axum", "redoc", "macros", "axum-extra-query"] }
schemars = { version = "0.8.10", features = ["uuid1"] }
dotenvy = "0.15.6"
reqwest = { version = "0.11.12", features = ["json", "native-tls-vendored"] }
config = "0.13.2"
once_cell = "1.16.0"
askama = "0.11"
pulldown-cmark = "0.9.2"
[features]
default = []
integration = []

[dev-dependencies]
tower = "0.4.13"
speculoos = "0.10.0"

[[test]]
name = "integration"
path = "tests/integration.rs"
required-features = ["integration"]
