###  Ping
GET http://localhost:3000

### Init a repository
POST http://localhost:3000/repository/init
Content-Type: application/json

{ "name" : "test" }

### Create user
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "okno",
  "email": "paul.delafosse@protonmail.com"
}

### Create ssh key
POST http://localhost:3000/users/ssh_key/add
Content-Type: application/json

{ "key" : "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCyhPNB0Grfs5JgDQp+6Drhl7kpZR/QxH9x9n4z6aOOCpxEkz1ikeivlN3ArBIMbSam+2w9LcZzg82YQA3+OlNr4zMl+JZVQcRgVRaPWZl9Pz84wy/CoUnmIOycrA+X7tY6BYJoVF1qgUBF1kr3z+maUggIhNIH9btdxH8H3+qqjNqUoLXJhmBgt3wCVQ/1g0k+EuGldHonj7t4yR0OtAkLHHVXnmfffbAl80o3+lkrZiibTtf8EgKNkWxZsJiA+oieWSLQYhGSlu77pOZP6kjWctBqRJt1n9Mixi3UxeSUDsAPfjiBwgFQqqjDWzUq6kPrnpIJ4wUxUa0F/5b20PKH9zFWjBrzd+lYEPB+fnYA80dCiNvKzqhT8q10VahqZ4YbI+gxX4z92Mj7IVi240NCq6aKQ5EpsKJpUcozJbtv6PXITHKbPZMlCziyXZiF9LGn+wXqyqLsyB3Ls2DrOpk/sgy1a/1F9+C2uULSvvhsP+1J0az3EHHFjTADYixsVrM= okno@havre" }