version: '3.9'

services:
  keycloakdb:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_PASSWORD: "keycloak"
    networks:
      - local-keycloak

  keycloak:
    image: jboss/keycloak:latest
    restart: unless-stopped
    depends_on:
      - keycloakdb
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloakdb
      DB_DATABASE: "keycloak"
      DB_USER: "keycloak"
      DB_PASSWORD: "keycloak"
      KEYCLOAK_IMPORT: /tmp/realm-export.json
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./../docker/realm-export.json:/tmp/realm-export.json
    networks:
      - local-keycloak
networks:
  local-keycloak: