[package]
name = "gill-db"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { workspace = true }
serde = { workspace = true }
chrono.workspace = true

[dev-dependencies]
speculoos.workspace = true
anyhow.workspace = true