domain = "bore.pub:37349"
debug = true
port = 3000

[database]
host = "postgres"
port = 5432
database = "gill_2"
user = "postgres"
password = "postgres"

[oauth_provider]
client_id = "gill"
client_secret = "8Nup063EeIOYzSsEyVZkbo67sUpIX0Bc"
provider = "https://keycloak.cloud.hoohoot.org"
user_info_url = "/auth/realms/hoohoot/protocol/openid-connect/userinfo"
auth_url = "/auth/realms/hoohoot/protocol/openid-connect/auth"
token_url = "/auth/realms/hoohoot/protocol/openid-connect/token"