[package]
name = "gill-markdown"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulldown-cmark = "0.9.2"
quick-xml = "0.27.1"

[dev-dependencies]
speculoos.workspace = true